[package]
name = "prosaic-vocab-code"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Code-analysis vocabulary module for the prosaic crate"

[dependencies]
prosaic-core = { version = "0.6.2", path = "../prosaic-core" }

[dev-dependencies]
prosaic-grammar-en = { version = "0.6.2", path = "../prosaic-grammar-en" }
prosaic-grammar-es = { version = "0.6.2", path = "../prosaic-grammar-es" }
