[workspace]
resolver = "2"
members = [
    "prosaic-common",
    "prosaic-core",
    "prosaic-grammar-de",
    "prosaic-grammar-en",
    "prosaic-grammar-es",
    "prosaic-derive",
    "prosaic-project",
    "prosaic-vocab-code",
    "prosaic-vocab-git",
    "prosaic-vocab-pr",
    "prosaic-vocab-release",
    "prosaic-wasm",
    "prosaic-cli",
    "prosaic-tracing",
]

[workspace.package]
version = "0.6.2"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/wildmason/prosaic"
