[package]
name = "nlg-derive"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Derive macros for the nlg crate"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
nlg-core = { path = "../nlg-core", default-features = false }
