mod language;
mod context;
mod error;
mod template;
mod engine;
mod builder;
mod discourse;
mod salience;
mod document;

pub use language::{Language, Tense, Person, Conjunction};
pub use context::{Context, Value};
pub use error::NlgError;
pub use template::{Template, Pipe, PipeArg};
pub use engine::{Engine, Variation, Strictness};
pub use builder::{Sentence, Clause, Subject, Voice, entity, named};
pub use context::IntoContext;
pub use discourse::{ListStyle, ReferenceForm};
pub use salience::{Salience, SalienceThresholds};
pub use document::{DocumentPlan, Paragraph};
