[package]
name = "prosaic-derive"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Derive macros for the prosaic crate"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"
prosaic-core = { path = "../prosaic-core", default-features = false }
